import { notFound } from "next/navigation";
import Link from "next/link";
import { supabase } from "@/lib/supabase";
import { AssetBody } from "@/components/AssetView";
import { CHANNELS, CHANNEL_LABELS } from "@/lib/channels";
import DiscordShare from "@/components/DiscordShare";

export const dynamic = "force-dynamic";

// Dynamic OG/Twitter metadata so shared links preview with the app's info.
export async function generateMetadata({ params }) {
  const { id } = await params;
  try {
    const { data: app } = await supabase()
      .from("apps")
      .select("name, pitch, category")
      .eq("id", id)
      .single();
    if (!app) return { title: "Launch kit — LaunchCopilot" };
    const title = `${app.name} — launch kit`;
    return {
      title: `${title} | LaunchCopilot`,
      description: app.pitch,
      openGraph: { title, description: app.pitch, siteName: "LaunchCopilot" },
      twitter: { card: "summary", title, description: app.pitch },
    };
  } catch {
    return { title: "Launch kit — LaunchCopilot" };
  }
}

// Public, read-only view of a generated launch kit — the growth loop:
// "here's what it wrote for MY app — try yours."
export default async function ShareKitPage({ params }) {
  const { id } = await params;
  const db = supabase();

  const [{ data: app }, { data: assets }, { data: plan }] = await Promise.all([
    db.from("apps").select("*").eq("id", id).single(),
    db.from("assets").select("*").eq("app_id", id),
    db.from("plans").select("*").eq("app_id", id).maybeSingle(),
  ]);

  if (!app) notFound();

  const byChannel = Object.fromEntries((assets ?? []).map((a) => [a.channel, a.content]));
  const phTagline = byChannel.product_hunt?.tagline;

  return (
    <div>
      <h1>{app.name} — launch kit</h1>
      <p className="lede">
        <span className="badge">{app.category}</span> &nbsp;{app.pitch}
      </p>
      <p className="hint">
        Generated by LaunchCopilot from ~20 seconds of app info. Every asset is
        written for its platform&apos;s real conventions — note how differently
        the same app speaks on Reddit vs the App Store.{" "}
        <Link href="/" style={{ color: "var(--accent)" }}>
          Generate yours →
        </Link>
      </p>

      <DiscordShare appName={app.name} tagline={phTagline} />

      {CHANNELS.filter(({ key }) => byChannel[key]).map(({ key, label, icon }) => (
        <div className="card" key={key}>
          <h3>
            {icon} {label}
          </h3>
          <AssetBody channel={key} content={byChannel[key]} />
        </div>
      ))}

      {plan?.days && (
        <>
          <h2>📅 7-day promotion plan</h2>
          <div className="card">
            {plan.days.map((d) => (
              <div className="plan-day" key={d.day}>
                <div className="day-num">Day {d.day}</div>
                <div>
                  <strong>{d.theme}</strong>
                  {(d.tasks ?? []).map((t, i) => (
                    <div className="plan-task" key={i}>
                      <span>☐</span>
                      <span>
                        {t.text}{" "}
                        <span className="chan">[{CHANNEL_LABELS[t.channel] ?? t.channel}]</span>
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </>
      )}
    </div>
  );
}
